package com.letscamping.model

import com.google.gson.JsonObject
import org.json.JSONObject
import java.io.Serializable

class GoCampsiteVO(c: JSONObject) {
    var contentId = 0 //콘텐츠 ID
    var facltNm = "" //야영장 명
    var lineIntro = "" //한줄소개
    var intro = "" //소개
    var allar = "" //전체면적
    var insrncAt = "" //영업배상책임보험 가입여부(Y:사용, N:미사용)
    var trsagntNo = "" //관광사업자 번호
    var bizrno = "" //사업자번호
    var facltDivNm = "" //사업주체.구분
    var mangeDivNm = "" //운영주체.관리주체(직영, 위탁)
    var mgcDiv = "" //운영기관.관리기관
    var manageSttus = "" //운영상태.관리상태
    var hvofBgnde = "" //호장기간.휴무기간 시작일
    var hvofEnddle = "" //휴장기간.휴무기간 종료일
    var featureNm = "" //특징
    var induty = "" //업종
    var lctCl = "" //입지구분
    var doNm = "" //도
    var sigunguNm = "" //시군구
    var zipcode = "" //우편번호
    var addr1 = "" //주소
    var addr2 = "" //주소상세
    var mapX = "" //경도
    var mapY = "" //위도
    var direction = "" //오시는 길 컨텐츠
    var tel = "" //전화
    var homepage = "" //홈페이지
    var resveUrl = "" //예약 페이지
    var resveCl = "" //예약구분
    var manageNmpr = "" //상주관리인원
    var gnrlSiteCo = "" //주요시설 일반 야영장
    var autoSiteCo = "" //주요시설 자동차야영장
    var glampSiteCo = "" //주요시설 글램핑
    var caramSiteCo = "" //주요시설 카라반
    var indvdlCaravSiteCo = "" //주요시설 개인 카라반
    var sitedStnc = "" //사이트간 거리
    var siteMg1Width = "" //사이트 크기1 가로
    var siteMg2Width = "" //사이트 크기2 가로
    var siteMg3Width = "" //사이트 크기3 가로
    var siteMg1Vrticl = "" //사이트 크기1 세로
    var siteMg2Vrticl = "" //사이트 크기2 세로
    var siteMg3Vrticl = "" //사이트 크기3 세로
    var siteMg1Co = "" //사이트 크기1 수량
    var siteMg2Co = "" //사이트 크기2 수량
    var siteMg3Co = "" //사이트 크기3 수량
    var siteBottomCl1 = "" //잔디
    var siteBottomCl2 = "" //파쇄석
    var siteBottomCl3 = "" //테크
    var siteBottomCl4 = "" //자갈
    var siteBottomCl5 = "" //맨흙
    var tooltip = "" //툴팁
    var glampInnerFclty = "" //글램핑-내부시설
    var caravInnerFclty = "" //카라반-내부시설
    var prmisnDe = "" //인허가일자
    var operPdCl = "" //운영기간
    var operDeCl = "" //운영일
    var trlerAcmpnyAt = "" //개인 트레일러 동반 여부(Y:사용, N:미사용)
    var caravAcmpnyAt = "" //개인 카라반 동반 여부(Y:사용, N:미사용)
    var toiletCo = "" //화장실 개수
    var swrmCo = "" //샤워실 개수
    var wtrplCo = "" //개수대 개수
    var brazierCl = "" //화로대
    var sbrsCl = "" //부대시설
    var sbrsEtc = "" //부대시설 기타
    var posblFcltyCl = "" //주변 이용 가능시설
    var posblFcltyEtc = "" //주변 이용 가능시설 기타
    var clturEventAt = "" //자체 문화행사 여부(Y:사용, N:미사용)
    var clturEvent = "" //자체 문화행사 명
    var exprnProgrmAt = "" //체험 프로그램 여부(Y:사용, N:미사용)
    var exprnProgrm = "" //체험 프로그램 명
    var extshrCo = "" //소화기 개수
    var frprvtWrppCo = "" //방화수 개수
    var frprvtSandCo = "" //방화사 개수
    var fireSensorCo = "" //화재감지기 개수
    var themaEnvrnCl = "" //테마환경
    var eqpmnLendCl = "" //캠핑 장비 대여
    var animalCmgCl = "" //애완동물 출입
    var tourEraCl = "" //여행시기
    var firstImageUrl = "" //대표이미지
    var createdtime = "" //등록일
    var modifiedtime = "" //수정일

    init {
        if (!c.isNull("contentId")) contentId = c.getInt("contentId")
        if (!c.isNull("facltNm")) facltNm = c.getString("facltNm")
        if (!c.isNull("lineIntro")) lineIntro = c.getString("lineIntro")
        if (!c.isNull("intro")) intro = c.getString("intro")
        if (!c.isNull("allar")) allar = c.getInt("allar").toString()
        if (!c.isNull("insrncAt")) insrncAt = c.getString("insrncAt")
        if (!c.isNull("trsagntNo")) trsagntNo = c["trsagntNo"].toString()
        if (!c.isNull("bizrno")) bizrno = c.getString("bizrno")
        if (!c.isNull("facltDivNm")) facltDivNm = c.getString("facltDivNm")
        if (!c.isNull("mangeDivNm")) mangeDivNm = c.getString("mangeDivNm")
        if (!c.isNull("mgcDiv")) mgcDiv = c.getString("mgcDiv")
        if (!c.isNull("manageSttus")) manageSttus = c.getString("manageSttus")
        if (!c.isNull("hvofBgnde")) hvofBgnde = c.getString("hvofBgnde")
        if (!c.isNull("hvofEnddle")) hvofEnddle = c.getString("hvofEnddle")
        if (!c.isNull("featureNm")) featureNm = c.getString("featureNm")
        if (!c.isNull("induty")) induty = c.getString("induty")
        if (!c.isNull("lctCl")) lctCl = c.getString("lctCl")
        if (!c.isNull("doNm")) doNm = c.getString("doNm")
        if (!c.isNull("sigunguNm")) sigunguNm = c.getString("sigunguNm")
        if (!c.isNull("zipcode")) zipcode = c["zipcode"].toString()
        if (!c.isNull("addr1")) addr1 = c.getString("addr1")
        if (!c.isNull("addr2")) addr2 = c["addr2"].toString()
        if (!c.isNull("mapX")) mapX = c.getLong("mapX").toString()
        if (!c.isNull("mapY")) mapY = c.getLong("mapY").toString()
        if (!c.isNull("direction")) direction = c.getString("direction")
        if (!c.isNull("tel")) tel = c.getString("tel")
        if (!c.isNull("homepage")) homepage = c.getString("homepage")
        if (!c.isNull("resveUrl")) resveUrl = c.getString("resveUrl")
        if (!c.isNull("resveCl")) resveCl = c.getString("resveCl")
        if (!c.isNull("manageNmpr")) manageNmpr = c.getInt("manageNmpr").toString()
        if (!c.isNull("gnrlSiteCo")) gnrlSiteCo = c.getInt("gnrlSiteCo").toString()
        if (!c.isNull("autoSiteCo")) autoSiteCo = c.getInt("autoSiteCo").toString()
        if (!c.isNull("glampSiteCo")) glampSiteCo = c.getInt("glampSiteCo").toString()
        if (!c.isNull("caramSiteCo")) caramSiteCo = c.getInt("caramSiteCo").toString()
        if (!c.isNull("indvdlCaravSiteCo")) indvdlCaravSiteCo = c.getInt("indvdlCaravSiteCo").toString()
        if (!c.isNull("sitedStnc")) sitedStnc = c.getInt("sitedStnc").toString()
        if (!c.isNull("siteMg1Width")) siteMg1Width = c.getInt("siteMg1Width").toString()
        if (!c.isNull("siteMg2Width")) siteMg2Width = c.getInt("siteMg2Width").toString()
        if (!c.isNull("siteMg3Width")) siteMg3Width = c.getInt("siteMg3Width").toString()
        if (!c.isNull("siteMg1Vrticl")) siteMg1Vrticl = c.getInt("siteMg1Vrticl").toString()
        if (!c.isNull("siteMg2Vrticl")) siteMg2Vrticl = c.getInt("siteMg2Vrticl").toString()
        if (!c.isNull("siteMg3Vrticl")) siteMg3Vrticl = c.getInt("siteMg3Vrticl").toString()
        if (!c.isNull("siteMg1Co")) siteMg1Co = c.getInt("siteMg1Co").toString()
        if (!c.isNull("siteMg2Co")) siteMg2Co = c.getInt("siteMg2Co").toString()
        if (!c.isNull("siteMg3Co")) siteMg3Co = c.getInt("siteMg3Co").toString()
        if (!c.isNull("siteBottomCl1")) siteBottomCl1 = c.getInt("siteBottomCl1").toString()
        if (!c.isNull("siteBottomCl2")) siteBottomCl2 = c.getInt("siteBottomCl2").toString()
        if (!c.isNull("siteBottomCl3")) siteBottomCl3 = c.getInt("siteBottomCl3").toString()
        if (!c.isNull("siteBottomCl4")) siteBottomCl4 = c.getInt("siteBottomCl4").toString()
        if (!c.isNull("siteBottomCl5")) siteBottomCl5 = c.getInt("siteBottomCl5").toString()
        if (!c.isNull("tooltip")) tooltip = c.getString("tooltip")
        if (!c.isNull("glampInnerFclty")) glampInnerFclty = c.getString("glampInnerFclty")
        if (!c.isNull("caravInnerFclty")) caravInnerFclty = c.getString("caravInnerFclty")
        if (!c.isNull("prmisnDe")) prmisnDe = c.getString("prmisnDe")
        if (!c.isNull("operPdCl")) operPdCl = c.getString("operPdCl")
        if (!c.isNull("operDeCl")) operDeCl = c.getString("operDeCl")
        if (!c.isNull("trlerAcmpnyAt")) trlerAcmpnyAt = c.getString("trlerAcmpnyAt")
        if (!c.isNull("caravAcmpnyAt")) caravAcmpnyAt = c.getString("caravAcmpnyAt")
        if (!c.isNull("toiletCo")) toiletCo = c.getInt("toiletCo").toString()
        if (!c.isNull("swrmCo")) swrmCo = c.getInt("swrmCo").toString()
        if (!c.isNull("wtrplCo")) wtrplCo = c.getInt("wtrplCo").toString()
        if (!c.isNull("brazierCl")) brazierCl = c.getString("brazierCl")
        if (!c.isNull("sbrsCl")) sbrsCl = c.getString("sbrsCl")
        if (!c.isNull("sbrsEtc")) sbrsEtc = c.getString("sbrsEtc")
        if (!c.isNull("posblFcltyCl")) posblFcltyCl = c.getString("posblFcltyCl")
        if (!c.isNull("posblFcltyEtc")) posblFcltyEtc = c.getString("posblFcltyEtc")
        if (!c.isNull("clturEventAt")) clturEventAt = c.getString("clturEventAt")
        if (!c.isNull("clturEvent")) clturEvent = c.getString("clturEvent")
        if (!c.isNull("exprnProgrmAt")) exprnProgrmAt = c.getString("exprnProgrmAt")
        if (!c.isNull("exprnProgrm")) exprnProgrm = c.getString("exprnProgrm")
        if (!c.isNull("extshrCo")) extshrCo = c.getInt("extshrCo").toString()
        if (!c.isNull("frprvtWrppCo")) frprvtWrppCo = c.getInt("frprvtWrppCo").toString()
        if (!c.isNull("frprvtSandCo")) frprvtSandCo = c.getInt("frprvtSandCo").toString()
        if (!c.isNull("fireSensorCo")) fireSensorCo = c.getInt("fireSensorCo").toString()
        if (!c.isNull("themaEnvrnCl")) themaEnvrnCl = c.getString("themaEnvrnCl")
        if (!c.isNull("eqpmnLendCl")) eqpmnLendCl = c.getString("eqpmnLendCl")
        if (!c.isNull("animalCmgCl")) animalCmgCl = c.getString("animalCmgCl")
        if (!c.isNull("tourEraCl")) tourEraCl = c.getString("tourEraCl")
        if (!c.isNull("firstImageUrl")) firstImageUrl = c.getString("firstImageUrl")
        if (!c.isNull("createdtime")) createdtime = c.getString("createdtime")
        if (!c.isNull("modifiedtime")) modifiedtime = c.getString("modifiedtime")
    }
}
